# Generated by Django 3.2 on 2022-02-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_usermail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='publication_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
