# Generated by Django 3.2 on 2022-02-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_mypublication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypublication',
            options={'verbose_name': 'публикация', 'verbose_name_plural': 'публикациии'},
        ),
    ]
