# Generated by Django 3.2 on 2022-02-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_mypublication_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyPublication',
        ),
    ]
